import{S as m,i as p}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function e(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const f="34465474-c3837bc3938f4efd53294c219",h="https://pixabay.com/api",y=async o=>{const r=new URLSearchParams({key:f,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}),s=`${h}/?${r.toString()}`;try{const e=await fetch(s);if(!e.ok)throw new Error("Network response was not ok");return await e.json()}catch(e){throw e}},c=document.querySelector(".gallery"),g=o=>new Promise((r,s)=>{const e=new Image;e.src=o,e.onload=()=>r(o),e.onerror=t=>s(t)}),w=async o=>{c.innerHTML="";try{const r=o.map(e=>g(e.webformatURL));await Promise.all(r),c.innerHTML=o.map(e=>`
          <a href="${e.largeImageURL}" class="gallery-item">
            <img src="${e.webformatURL}" alt="${e.tags}">
            <div class="info">
              <div><p>Likes</p><p>${e.likes}</p></div>
              <div><p>Views</p><p>${e.views}</p></div>
              <div><p>Comments</p><p>${e.comments}</p></div>
              <div><p>Downloads</p><p>${e.downloads}</p></div>
            </div>
          </a>`).join(""),new m(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",animationSpeed:250,fadeSpeed:250}).refresh()}catch{n("Failed to load images. Please try again.")}},n=o=>{p.error({message:o,position:"topRight",color:"#EF4040",messageColor:"white",iconColor:"white",timeout:1e4})},u=document.querySelector(".search-form"),b=document.querySelector('.search-form input[name="search"]'),l=document.querySelector('.search-form button[type="submit"]'),d=document.querySelector(".loader"),v=async o=>{o.preventDefault();const r=b.value.trim();if(!r){n("Please enter a search query.");return}l.disabled=!0,d.style.display="flex";try{const s=await y(r);s.hits.length===0?n("Sorry, there are no images matching your search query. Please try again!"):await w(s.hits)}catch(s){n("An error occurred while fetching images. Please try again later."),console.error("Error fetching images:",s)}finally{d.style.display="none",l.disabled=!1,u.reset()}};u.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
